Update spx

diff --git a/spx b/spx
--- a/spx
+++ b/spx
@@ -1,15 +1,5 @@
 #!/bin/bash
 
-cpl() {
-    if [[ x"${release}" == x"centos" ]]; then
-        sudo yum install dialog -y &> /dev/null
-    else
-        sudo apt-get install dialog -y &> /dev/null
-    fi
-}
-
-if ! dpkg-query -W -f='${Status}' dialog | grep "ok installed" &> /dev/null; then cpl; fi
-
 red='\033[0;31m'
 green='\033[0;32m'
 yellow='\033[0;33m'
@@ -18,236 +8,176 @@ plain='\033[0m'
 cur_dir=$(pwd)
 
 # check root
-if [ $EUID -ne 0 ]
-   then dialog --title "Error" --backtitle "X-UI Installer" --msgbox "Must be root to run this script !" 6 39
-   clear
-   exit
-fi
+[[ $EUID -ne 0 ]] && echo -e "${red}Fatal error: ${plain} Please run this script with root privilege \n " && exit 1
 
-# check os
-if [[ -f /etc/redhat-release ]]; then
-    release="centos"
-elif cat /etc/issue | grep -Eqi "debian"; then
-    release="debian"
-elif cat /etc/issue | grep -Eqi "armbian"; then
-    release="armbian"
-elif cat /etc/issue | grep -Eqi "ubuntu"; then
-    release="ubuntu"
-elif cat /etc/issue | grep -Eqi "centos|red hat|redhat"; then
-    release="centos"
-elif cat /proc/version | grep -Eqi "debian"; then
-    release="debian"
-elif cat /proc/version | grep -Eqi "ubuntu"; then
-    release="ubuntu"
-elif cat /proc/version | grep -Eqi "centos|red hat|redhat"; then
-    release="centos"
+# Check OS and set release variable
+if [[ -f /etc/os-release ]]; then
+    source /etc/os-release
+    release=$ID
+elif [[ -f /usr/lib/os-release ]]; then
+    source /usr/lib/os-release
+    release=$ID
 else
-    dialog --title "Error" --backtitle "X-UI Installer" --msgbox "System version not detected, please contact the script author !" 6 39
-    clear
-    exit
+    echo "Failed to check the system OS, please contact the author!" >&2
+    exit 1
 fi
+echo "The OS release is: $release"
 
-arch=$(arch)
-
-if [[ $arch == "x86_64" || $arch == "x64" || $arch == "amd64" ]]; then
-    arch="x86_64"
-elif [[ $arch == "aarch64" || $arch == "arm64" ]]; then
-    arch="aarch64"
-elif [[ $arch == "s390x" ]]; then
-    arch="s390x"
-elif [[ $arch == "riscv64" ]]; then
-    arch="riscv64"
-else
-    arch="x86_64"
-    dialog --title "Warning" --backtitle "X-UI Installer" --msgbox "Failed to detect schema, use default schema: ${arch}" 6 39
-    clear
-fi
-
-dialog --title "Infomation" --backtitle "X-UI Installer" --msgbox "Your CPU arch: ${arch}" 6 39
-clear
-
-if [ $(getconf WORD_BIT) != '32' ] && [ $(getconf LONG_BIT) != '64' ]; then
-    dialog --title "Error" --backtitle "X-UI Installer" --msgbox "This software does not support 32-bit system (x86), please use 64-bit system (x86_64), if the detection is wrong, please contact the author" 6 39
-    clear
-    exit
-fi
+arch3xui() {
+    case "$(uname -m)" in
+    x86_64 | x64 | amd64) echo 'amd64' ;;
+    armv8 | arm64 | aarch64) echo 'arm64' ;;
+    *) echo -e "${green}Unsupported CPU architecture! ${plain}" && rm -f install.sh && exit 1 ;;
+    esac
+}
+echo "arch: $(arch3xui)"
 
 os_version=""
+os_version=$(grep -i version_id /etc/os-release | cut -d \" -f2 | cut -d . -f1)
 
-# os version
-if [[ -f /etc/os-release ]]; then
-    os_version=$(awk -F'[= ."]' '/VERSION_ID/{print $3}' /etc/os-release)
-fi
-if [[ -z "$os_version" && -f /etc/lsb-release ]]; then
-    os_version=$(awk -F'[= ."]+' '/DISTRIB_RELEASE/{print $2}' /etc/lsb-release)
-fi
-
-if [[ x"${release}" == x"centos" ]]; then
-    if [[ ${os_version} -le 6 ]]; then
-        dialog --title "Error" --backtitle "X-UI Installer" --msgbox "Please use CentOS 7 or higher!" 6 39
-        clear
-        exit
-    fi
-elif [[ x"${release}" == x"ubuntu" ]]; then
-    if [[ ${os_version} -lt 16 ]]; then
-        dialog --title "Error" --backtitle "X-UI Installer" --msgbox "Please use Ubuntu 16 or later!" 6 39
-        clear
-        exit
-    fi
-elif [[ x"${release}" == x"debian" ]]; then
+if [[ "${release}" == "centos" ]]; then
     if [[ ${os_version} -lt 8 ]]; then
-        dialog --title "Error" --backtitle "X-UI Installer" --msgbox "Please use Debian 8 or higher!" 6 39
-        clear
-        exit
+        echo -e "${red} Please use CentOS 8 or higher ${plain}\n" && exit 1
     fi
-fi
+elif [[ "${release}" == "ubuntu" ]]; then
+    if [[ ${os_version} -lt 18 ]]; then
+        echo -e "${red}please use Ubuntu 20 or higher version!${plain}\n" && exit 1
+    fi
 
-# install_base() {
-#     if [[ x"${release}" == x"centos" ]]; then
-#         yum install wget curl tar newt -y
-#     else
-#         apt-get install wget curl tar whiptail -y
-#     fi
-# }
+elif [[ "${release}" == "fedora" ]]; then
+    if [[ ${os_version} -lt 36 ]]; then
+        echo -e "${red}please use Fedora 36 or higher version!${plain}\n" && exit 1
+    fi
+
+elif [[ "${release}" == "debian" ]]; then
+    if [[ ${os_version} -lt 10 ]]; then
+        echo -e "${red} Please use Debian 10 or higher ${plain}\n" && exit 1
+    fi
+elif [[ "${release}" == "arch" ]]; then
+    echo "OS is ArchLinux"
+
+else
+    echo -e "${red}Failed to check the OS version, please contact the author!${plain}" && exit 1
+fi
 
 install_base() {
-msgs=("Preparing install..."
-      "Starting wget installation..."
-      "Starting curl installation..."
-      "Starting tar installation..."
-     )
-if [[ x"${release}" == x"centos" ]]; then
-    commands=("yum install wget -y"
-              "yum install curl -y"
-              "yum install tar -y"
-              )
-else
-    commands=("apt-get install wget -y"
-              "apt-get install curl -y"
-              "apt-get install tar -y"
-              )
-fi
-n=${#commands[@]}
-i=0
-while [ "$i" -lt "$n" ]; do
-    pct=$(( i * 100 / n ))
-    echo XXX
-    echo $i
-    echo "${msgs[i]}"
-    echo XXX
-    echo "$pct"
-    eval "${commands[i]}"
-    i=$((i + 1))
-done | dialog --title "X-UI Installer Packages" --backtitle "X-UI Installer" --gauge "Please wait install ..." 10 60 0
-clear
-}
-
-config_after_install() {
-    config_account=""
-    config_password=""
-    config_port=""
-    dialog --title "Warning" \
-           --backtitle "X-UI Installer" \
-           --yesno "Are you sure you want Setting account install X-UI ?" 7 60
-    response=$?
-    case $response in
-       0)
-        config_account=""
-        config_password=""
-        config_port=""
-        dialog --title "Warning" \
-               --backtitle "X-UI Installer" --ok-label "OK" \
-               --stdout \
-               --form "Settings X-UI Config" 10 60 3 \
-                      "username: " 1 1 "$config_account" 1 15 30 0 \
-                      "password: " 2 1 "$config_password" 2 15 30 0 \
-                      "port: " 3 1 "$config_port" 3 15 30 0 > /tmp/xuioutput.txt
-        config_account=$(cat /tmp/xuioutput.txt | head -1)
-        config_password=$(cat /tmp/xuioutput.txt | head -2 | tail -1)
-        config_port=$(cat /tmp/xuioutput.txt | head -3 | tail -1)
-        rm -rf /tmp/xuioutput.txt
-
-        # config_account=$(whiptail --inputbox "Please set your account name" 8 39 --title "Create Account" 3>&1 1>&2 2>&3)
-        [[ ! -z "${config_account}" ]] || config_account="admin"
-        # config_password=$(whiptail --passwordbox "Please set your password" 8 39 --title "Create Account" 3>&1 1>&2 2>&3)
-        [[ ! -z "${config_password}" ]] || config_password="admin"
-        # config_port=$(whiptail --inputbox "Please set your port" 8 39 --title "Setup X-UI" 3>&1 1>&2 2>&3)
-        [[ ! -z "${config_port}" ]] || config_port="54321"
-        /usr/local/x-ui/x-ui setting -username ${config_account} -password ${config_password}
-        /usr/local/x-ui/x-ui setting -port ${config_port}
-        clear
-        dialog --title "Complete" \
-               --backtitle "X-UI Installer" \
-               --msgbox "X-UI Settings Complete" 8 78
-        clear
-        ;;
-       1)
-        dialog --title "Complete" \
-               --backtitle "X-UI Installer" \
-               --msgbox "Cancelled, all setting items are default settings, please modify in time.\nDefault username: admin \nDefault password: admin \nDefault port: 54321" 12 80
-        clear
-        ;;
-       255) echo "[ESC] key pressed."
-        ;;
+    case "${release}" in
+        centos|fedora)
+            yum install -y -q wget curl tar
+            ;;
+        arch)
+            pacman -Syu --noconfirm wget curl tar
+            ;;
+        *)
+            apt install -y -q wget curl tar
+            ;;
     esac
 }
 
+
+# This function will be called when user installed x-ui out of sercurity
+config_after_install() {
+    echo -e "${yellow}Install/update finished! For security it's recommended to modify panel settings ${plain}"
+    read -p "Do you want to continue with the modification [y/n]? ": config_confirm
+    if [[ "${config_confirm}" == "y" || "${config_confirm}" == "Y" ]]; then
+        read -p "Please set up your username:" config_account
+        echo -e "${yellow}Your username will be:${config_account}${plain}"
+        read -p "Please set up your password:" config_password
+        echo -e "${yellow}Your password will be:${config_password}${plain}"
+        read -p "Please set up the panel port:" config_port
+        echo -e "${yellow}Your panel port is:${config_port}${plain}"
+        echo -e "${yellow}Initializing, please wait...${plain}"
+        /usr/local/x-ui/x-ui setting -username ${config_account} -password ${config_password}
+        echo -e "${yellow}Account name and password set successfully!${plain}"
+        /usr/local/x-ui/x-ui setting -port ${config_port}
+        echo -e "${yellow}Panel port set successfully!${plain}"
+    else
+        echo -e "${red}cancel...${plain}"
+        if [[ ! -f "/etc/x-ui/x-ui.db" ]]; then
+            local usernameTemp=$(head -c 6 /dev/urandom | base64)
+            local passwordTemp=$(head -c 6 /dev/urandom | base64)
+            /usr/local/x-ui/x-ui setting -username ${usernameTemp} -password ${passwordTemp}
+            echo -e "this is a fresh installation,will generate random login info for security concerns:"
+            echo -e "###############################################"
+            echo -e "${green}username:${usernameTemp}${plain}"
+            echo -e "${green}password:${passwordTemp}${plain}"
+            echo -e "###############################################"
+            echo -e "${red}if you forgot your login info,you can type x-ui and then type 7 to check after installation${plain}"
+        else
+            echo -e "${red} this is your upgrade,will keep old settings,if you forgot your login info,you can type x-ui and then type 7 to check${plain}"
+        fi
+    fi
+    /usr/local/x-ui/x-ui migrate
+}
+
 install_x-ui() {
-    systemctl stop x-ui
     cd /usr/local/
 
     if [ $# == 0 ]; then
-        last_version=$(curl -Ls "https://api.github.com/repos/X-UI-Unofficial/release/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
+        last_version=$(curl -Ls "https://api.github.com/repos/MHSanaei/3x-ui/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
         if [[ ! -n "$last_version" ]]; then
-            dialog --title "Error" --backtitle "X-UI Installer" --msgbox "The failure of the X-UI version may be beyond the GitHub API limit, please try it later, or manually specify the X-UI version installation." 6 39
-            clear
-            exit
+            echo -e "${red}Failed to fetch x-ui version, it maybe due to Github API restrictions, please try it later${plain}"
+            exit 1
         fi
-        wget -N --no-check-certificate -O /usr/local/x-ui-linux-x86_64.tar.gz https://github.com/X-UI-Unofficial/release/releases/download/230403_v1/x-ui-linux-x86_64.tar.gz 2>&1 |  stdbuf -o0 awk '/[.] +[0-9][0-9]?[0-9]?%/ { print substr($0,63,3) }' | dialog --title "Download..." --backtitle "X-UI Installer" --gauge "Download X-UI ..." 6 50 0
+        echo -e "Got x-ui latest version: ${last_version}, beginning the installation..."
+        wget -N --no-check-certificate -O /usr/local/x-ui-linux-$(arch3xui).tar.gz https://github.com/MHSanaei/3x-ui/releases/download/${last_version}/x-ui-linux-$(arch3xui).tar.gz
         if [[ $? -ne 0 ]]; then
-            dialog --title "Error" --backtitle "X-UI Installer" --msgbox "Failed to download x-ui, please make sure your server can download Github files." 6 39
-            clear
-            exit
+            echo -e "${red}Downloading x-ui failed, please be sure that your server can access Github ${plain}"
+            exit 1
         fi
     else
         last_version=$1
-        url="https://github.com/X-UI-Unofficial/release/releases/download/230403_v1/x-ui-linux-${arch}.tar.gz"
-        wget -N --no-check-certificate -O /usr/local/x-ui-linux-x86_64.tar.gz ${url} 2>&1 |  stdbuf -o0 awk '/[.] +[0-9][0-9]?[0-9]?%/ { print substr($0,63,3) }' | dialog --title "Download..." --backtitle "X-UI Installer" --gauge "Download X-UI ..." 6 50 0
+        url="https://github.com/MHSanaei/3x-ui/releases/download/${last_version}/x-ui-linux-$(arch3xui).tar.gz"
+        echo -e "Begining to install x-ui $1"
+        wget -N --no-check-certificate -O /usr/local/x-ui-linux-$(arch3xui).tar.gz ${url}
         if [[ $? -ne 0 ]]; then
-            dialog --title "Complete" --backtitle "X-UI Installer" --msgbox "Failed to download x-ui v.gunx, please make sure this version exists." 6 39
-            clear
-            exit
+            echo -e "${red}Download x-ui $1 failed,please check the version exists ${plain}"
+            exit 1
         fi
     fi
 
     if [[ -e /usr/local/x-ui/ ]]; then
+        systemctl stop x-ui
         rm /usr/local/x-ui/ -rf
     fi
 
-    if [[ -e /usr/bin/x-ui/ ]]; then
-        rm /usr/bin/x-ui -rf
-    fi
-
-    tar zxf x-ui-linux-x86_64.tar.gz
-    rm x-ui-linux-x86_64.tar.gz -f
+    tar zxvf x-ui-linux-$(arch3xui).tar.gz
+    rm x-ui-linux-$(arch3xui).tar.gz -f
     cd x-ui
-    chmod +x x-ui bin/xray-linux-${arch}
+    chmod +x x-ui bin/xray-linux-$(arch3xui)
     cp -f x-ui.service /etc/systemd/system/
+    wget --no-check-certificate -O /usr/bin/x-ui https://raw.githubusercontent.com/MHSanaei/3x-ui/main/x-ui.sh
     chmod +x /usr/local/x-ui/x-ui.sh
     chmod +x /usr/bin/x-ui
-    cp -r /usr/local/x-ui/x-ui.sh /usr/bin/x-ui
-    if [[ $arch == "aarch64" || $arch == "arm64" ]]; then
-       mv /usr/local/x-ui/bin/xray-linux-aarch64 /usr/local/x-ui/bin/xray-linux-arm64
-    elif [[ $arch == "x86_64" || $arch == "x64" || $arch == "amd64" ]]; then
-       mv /usr/local/x-ui/bin/xray-linux-x86_64 /usr/local/x-ui/bin/xray-linux-amd64
-    fi
     config_after_install
+    #echo -e "If it is a new installation, the default web port is ${green}2053${plain}, The username and password are ${green}admin${plain} by default"
+    #echo -e "Please make sure that this port is not occupied by other procedures,${yellow} And make sure that port 2053 has been released${plain}"
+    #    echo -e "If you want to modify the 2053 to other ports and enter the x-ui command to modify it, you must also ensure that the port you modify is also released"
+    #echo -e ""
+    #echo -e "If it is updated panel, access the panel in your previous way"
+    #echo -e ""
     systemctl daemon-reload
     systemctl enable x-ui
     systemctl start x-ui
-    dialog --title "Complete" --backtitle "X-UI Installer" --msgbox "Install X-UI Complete: 230403_v1 by.gunx \nUse command x-ui for more infomation." 8 45
+    echo -e "${green}x-ui ${last_version}${plain} installation finished, it is running now..."
+    echo -e ""
+    echo -e "x-ui control menu usages: "
+    echo -e "----------------------------------------------"
+    echo -e "x-ui              - Enter     Admin menu"
+    echo -e "x-ui start        - Start     x-ui"
+    echo -e "x-ui stop         - Stop      x-ui"
+    echo -e "x-ui restart      - Restart   x-ui"
+    echo -e "x-ui status       - Show      x-ui status"
+    echo -e "x-ui enable       - Enable    x-ui on system startup"
+    echo -e "x-ui disable      - Disable   x-ui on system startup"
+    echo -e "x-ui log          - Check     x-ui logs"
+    echo -e "x-ui banlog       - Check Fail2ban ban logs"
+    echo -e "x-ui update       - Update    x-ui"
+    echo -e "x-ui install      - Install   x-ui"
+    echo -e "x-ui uninstall    - Uninstall x-ui"
+    echo -e "----------------------------------------------"
 }
-dialog --title "Complete" --backtitle "X-UI Installer" --msgbox "Start install X-UI" 8 45
+
+echo -e "${green}Running...${plain}"
 install_base
 install_x-ui $1
-clear
