Update conexao

diff --git a/MODULOS/conexao b/MODULOS/conexao
--- a/MODULOS/conexao
+++ b/MODULOS/conexao
@@ -77,67 +77,67 @@ for pton in `echo -e "$PT" | cut -d: -f2 | cut -d' ' -f1 | uniq`; do
 done
 }
 
-inst_sqd (){
-if netstat -nltp|grep 'squid' 1>/dev/null 2>/dev/null;then
-	echo -e "\E[41;1;37m            ลบ SQUID PROXY              \E[0m"
-	echo ""
-	echo -ne "\033[1;32mต้องการลบ SQUID \033[1;31m? \033[1;33m[y/n]:\033[1;37m "; read resp
-	if [[ "$resp" = 'y' ]]; then
-		echo -e "\n\033[1;32mลบ SQUID PROXY !\033[0m"
-		echo ""
-		rem_sqd () 
-		{
-		if [[ -d "/etc/squid/" ]]; then
-			apt-get remove squid -y
-			apt-get purge squid -y
-			rm -rf /etc/squid
-		fi
-		if [[ -d "/etc/squid3/" ]]; then
-			apt-get remove squid3 -y
-			apt-get purge squid3 -y
-			rm -rf /etc/squid3
-		fi
-	    }
-	    fun_bar 'rem_sqd'
-		echo -e "\n\033[1;32mลบ SQUID PROXY สำเร็จ !\033[0m"
-		sleep 3.5s
-		clear
-		fun_conexao
-	else
-		echo -e "\n\033[1;31mกลับ...\033[0m"
-		sleep 3
-		clear
-		fun_conexao
-	fi
-else
-clear
-echo -e "\E[44;1;37m              ติดตั้ง SQUID PROXY               \E[0m"
-echo ""
-IP=$(wget -qO- ipv4.icanhazip.com)
-echo -ne "\033[1;32mกด Enter เพื่อยืนยัน IP คุณ: \033[1;37m"; read -e -i $IP ipdovps
-if [[ -z "$ipdovps" ]];then
-echo -e "\n\033[1;31mIP ไม่ถูกต้อง\033[1;32m"
-echo ""
-read -p "ป้อน IP ของคุณ: " IP
-fi
-echo -e "\n\033[1;33mPort ใดที่คุณต้องการใช้กับ SQUID \033[1;31m?"
-echo -e "\n\033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mกำหนด Port ตามลำดับ \033[1;33mEX: \033[1;37m80 8080 8799 3128"
-echo ""
-echo -ne "\033[1;32mPort\033[1;37m: "; read portass
-if [[ -z "$portass" ]]; then
-	echo -e "\n\033[1;31mPort ไม่ถูกต้อง!"
-	sleep 3
-	fun_conexao
-fi
-
-
-
-for porta in $(echo -e $portass); do
+inst_sqd() {
+		if netstat -nltp | grep 'squid' 1>/dev/null 2>/dev/null; then
+			echo -e "\E[41;1;37m            REMOVER SQUID PROXY              \E[0m"
+			echo ""
+			echo -ne "\033[1;32mREALMENTE DESEJA REMOVER O SQUID \033[1;31m? \033[1;33m[s/n]:\033[1;37m "
+			read resp
+			[[ "$resp" = 's' ]] && {
+				echo -e "\n\033[1;32mREMOVENDO O SQUID PROXY !\033[0m"
+				echo ""
+				rem_sqd() {
+					[[ -d "/etc/squid" ]] && {
+						apt-get remove squid -y >/dev/null 2>&1
+						apt-get purge squid -y >/dev/null 2>&1
+						rm -rf /etc/squid >/dev/null 2>&1
+					}
+					[[ -d "/etc/squid3" ]] && {
+						apt-get remove squid3 -y >/dev/null 2>&1
+						apt-get purge squid3 -y >/dev/null 2>&1
+						rm -rf /etc/squid3 >/dev/null 2>&1
+						apt autoremove -y >/dev/null 2>&1
+					}
+				}
+				fun_bar 'rem_sqd'
+				echo -e "\n\033[1;32mSQUID REMOVIDO COM SUCESSO !\033[0m"
+				sleep 2
+				clear
+				fun_conexao
+			} || {
+				echo -e "\n\033[1;31mRetornando...\033[0m"
+				sleep 2
+				clear
+				fun_conexao
+			}
+		else
+			clear
+			echo -e "\E[44;1;37m              INSTALADOR SQUID                \E[0m"
+			echo ""
+			IP=$(wget -qO- ipv4.icanhazip.com)
+			echo -ne "\033[1;32mPARA CONTINUAR CONFIRME SEU IP: \033[1;37m"
+			read -e -i $IP ipdovps
+			[[ -z "$ipdovps" ]] && {
+				echo -e "\n\033[1;31mIP invalido\033[1;32m"
+				echo ""
+				read -p "Digite seu IP: " IP
+			}
+			echo -e "\n\033[1;33mQUAIS PORTAS DESEJA ULTILIZAR NO SQUID \033[1;31m?"
+			echo -e "\n\033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mDEFINA AS PORTAS EM SEQUENCIA \033[1;33mEX: \033[1;37m80 8080"
+			echo ""
+			echo -ne "\033[1;32mINFORME AS PORTAS\033[1;37m: "
+			read portass
+			[[ -z "$portass" ]] && {
+				echo -e "\n\033[1;31mPorta invalida!"
+				sleep 3
+				fun_conexao
+			}
+			for porta in $(echo -e $portass); do
 				verif_ptrs $porta
 			done
 			[[ $(grep -wc '14' /etc/issue.net) != '0' ]] || [[ $(grep -wc '8' /etc/issue.net) != '0' ]] && {
 				echo -e "\n\033[1;32mINSTALANDO SQUID PROXY\033[0m\n"
-				fun_bar 'apt update -y' "apt install squid -yy"
+				fun_bar 'apt update -y' "apt install squid3 -y"
 			} || {
 				echo -e "\n\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mSQUID VERSAO 3.3.X\n\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mSQUID VERSAO 3.5.X\033[0m\n"
 				read -p "$(echo -e "\033[1;32mINFORME UMA OPÇÃO \033[1;37m: ")" -e -i 1 opc
@@ -167,52 +167,35 @@ for porta in $(echo -e $portass); do
 				sleep 2
 				fun_conexao
 			fi
-cat <<-EOF >$var_pay
+			cat <<-EOF >$var_pay
 				.whatsapp.net/
 				.facebook.net/
 				.twitter.com/
 				.speedtest.net/
 			EOF
 			cat <<-EOF >$var_sqd
-acl localhost src 127.0.0.1/32 ::1
-acl to_localhost dst 127.0.0.0/8 0.0.0.0/32 ::1
-acl localnet src 10.0.0.0/8
-acl localnet src 172.16.0.0/12
-acl localnet src 192.168.0.0/16
-acl url1 dstdomain -i 127.0.0.1
-acl payload url_regex -i "$var_pay"
-acl SSL_ports port 443
-acl Safe_ports port 80
-acl Safe_ports port 21
-acl Safe_ports port 443
-acl Safe_ports port 70
-acl Safe_ports port 210
-acl Safe_ports port 1025-65535
-acl Safe_ports port 280
-acl Safe_ports port 488
-acl Safe_ports port 591
-acl Safe_ports port 777
-acl CONNECT method CONNECT
-acl SSH dst $ipdovps-$ipdovps/255.255.255.255
-http_access allow SSH
-http_access allow payload
-http_access allow localnet
-http_access allow localhost
-http_access allow url1
-http_access deny all
-refresh_pattern ^ftp:           1440    20%     10080
-refresh_pattern ^gopher:        1440    0%      1440
-refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
-refresh_pattern .               0       20%     4320
-     #Portas
-EOF
-for Pts in $(echo -e $portass); do
+				acl url1 dstdomain -i 127.0.0.1
+				acl url2 dstdomain -i localhost
+				acl url3 dstdomain -i $ipdovps
+				acl url4 dstdomain -i /SSHPLUS?
+				acl payload url_regex -i "$var_pay"
+				acl all src 0.0.0.0/0
+				http_access allow url1
+				http_access allow url2
+				http_access allow url3
+				http_access allow url4
+				http_access allow payload
+				http_access deny all
+				 
+				#Portas
+			EOF
+			for Pts in $(echo -e $portass); do
 				echo -e "http_port $Pts" >>$var_sqd
 				[[ -f "/usr/sbin/ufw" ]] && ufw allow $Pts/tcp
 			done
 			cat <<-EOF >>$var_sqd
 				#Nome squid
-				visible_hostname LiLGunX
+				visible_hostname SSHPLUS 
 				via off
 				forwarded_for off
 				pipeline_prefetch off
@@ -236,111 +219,6 @@ for Pts in $(echo -e $portass); do
 			sleep 2.5s
 			fun_conexao
 		fi
-	}
-for porta in $(echo -e $portass); do
-				verif_ptrs $porta
-			done
-			[[ $(grep -wc '14' /etc/issue.net) != '0' ]] || [[ $(grep -wc '8' /etc/issue.net) != '0' ]] && {
-				echo -e "\n\033[1;32mINSTALANDO SQUID PROXY\033[0m\n"
-				fun_bar 'apt update -y' "apt install squid -yy"
-			} || {
-				echo -e "\n\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mSQUID VERSAO 3.3.X\n\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mSQUID VERSAO 3.5.X\033[0m\n"
-				read -p "$(echo -e "\033[1;32mINFORME UMA OPÇÃO \033[1;37m: ")" -e -i 1 opc
-				[[ -z "$opc" ]] && {
-					echo -e "\n\033[1;31mOpcao invalida!"
-					sleep 2
-					fun_conexao
-				}
-				[[ "$opc" != '1' ]] && {
-					[[ "$opc" != '2' ]] && {
-						echo -e "\n\033[1;31mOpcao invalida !"
-						sleep 2
-						fun_conexao
-					}
-				}
-				echo -e "\n\033[1;32mINSTALANDO SQUID PROXY\033[0m\n"
-				fun_bar 'apt update -y' "instsqd $opc"
-			}
-			if [[ -d "/etc/squid/" ]]; then
-				var_sqd="/etc/squid/squid.conf"
-				var_pay="/etc/squid/payload.txt"
-			elif [[ -d "/etc/squid3/" ]]; then
-				var_sqd="/etc/squid3/squid.conf"
-				var_pay="/etc/squid3/payload.txt"
-			else
-				echo -e "\n\033[1;33m[\033[1;31mERRO\033[1;33m]\033[1;37m: \033[1;33mO SQUID PROXY CORROMPEU\033[0m"
-				sleep 2
-				fun_conexao
-			fi
-cat <<-EOF >$var_pay
-				.whatsapp.net/
-				.facebook.net/
-				.twitter.com/
-				.speedtest.net/
-			EOF
-			cat <<-EOF >$var_sqd
-acl localhost src 127.0.0.1/32 ::1
-acl to_localhost dst 127.0.0.0/8 0.0.0.0/32 ::1
-acl localnet src 10.0.0.0/8
-acl localnet src 172.16.0.0/12
-acl localnet src 192.168.0.0/16
-acl url1 dstdomain -i 127.0.0.1
-acl payload url_regex -i "$var_pay"
-acl SSL_ports port 443
-acl Safe_ports port 80
-acl Safe_ports port 21
-acl Safe_ports port 443
-acl Safe_ports port 70
-acl Safe_ports port 210
-acl Safe_ports port 1025-65535
-acl Safe_ports port 280
-acl Safe_ports port 488
-acl Safe_ports port 591
-acl Safe_ports port 777
-acl CONNECT method CONNECT
-acl SSH dst $ipdovps-$ipdovps/255.255.255.255
-http_access allow SSH
-http_access allow payload
-http_access allow localnet
-http_access allow localhost
-http_access allow url1
-http_access deny all
-refresh_pattern ^ftp:           1440    20%     10080
-refresh_pattern ^gopher:        1440    0%      1440
-refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
-refresh_pattern .               0       20%     4320
-     #Portas
-EOF
-for Pts in $(echo -e $portass); do
-				echo -e "http_port $Pts" >>$var_sqd
-				[[ -f "/usr/sbin/ufw" ]] && ufw allow $Pts/tcp
-			done
-			cat <<-EOF >>$var_sqd
-				#Nome squid
-				visible_hostname LiLGunX
-				via off
-				forwarded_for off
-				pipeline_prefetch off
-			EOF
-			sqd_conf() {
-				[[ -d "/etc/squid/" ]] && {
-					service ssh restart
-					/etc/init.d/squid restart
-					service squid restart
-				}
-				[[ -d "/etc/squid3/" ]] && {
-					service ssh restart
-					/etc/init.d/squid3 restart
-					service squid3 restart
-				}
-			}
-			echo -e "\n\033[1;32mCONFIGURANDO SQUID PROXY\033[0m"
-			echo ""
-			fun_bar 'sqd_conf'
-			echo -e "\n\033[1;32mSQUID INSTALADO COM SUCESSO!\033[0m"
-			sleep 2.5s
-			fun_conexao
-		
 	}
 
 addpt_sqd () {
