Update conexao

diff --git a/MODULOS/conexao b/MODULOS/conexao
--- a/MODULOS/conexao
+++ b/MODULOS/conexao
@@ -670,44 +670,44 @@ refresh_pattern .               0       20%     4320
 	inst_ssl() {
 		if netstat -nltp | grep 'stunnel4' 1>/dev/null 2>/dev/null; then
 			[[ $(netstat -nltp | grep 'stunnel4' | wc -l) != '0' ]] && sslt=$(netstat -nplt | grep stunnel4 | awk {'print $4'} | awk -F ":" {'print $2'} | xargs) || sslt="\033[1;31mINDISPONIVEL"
-			echo -e "\E[44;1;37m              จัดการ SSL TUNNEL               \E[0m"
+			echo -e "\E[44;1;37m              GERENCIAR SSL TUNNEL               \E[0m"
 			echo -e "\n\033[1;33mPORTAS\033[1;37m: \033[1;32m$sslt"
 			echo ""
-			echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mเปลี่ยน PORT SSL TUNNEL\033[0m"
-			echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mถอดติดตั้ง SSL TUNNEL\033[0m"
-			echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mย้อนกลับ\033[0m"
+			echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mALTERAR PORTA SSL TUNNEL\033[0m"
+			echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mREMOVER SSL TUNNEL\033[0m"
+			echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR\033[0m"
 			echo ""
-			echo -ne "\033[1;32mSELLECT OPTION \033[1;33m?\033[1;37m "
+			echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;37m "
 			read resposta
 			echo ""
 			[[ "$resposta" = '1' ]] && {
-				echo -ne "\033[1;32mพิมพ์ PORTต้องการใช้\033[1;33m?\033[1;37m "
+				echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;33m?\033[1;37m "
 				read porta
 				echo ""
 				[[ -z "$porta" ]] && {
 					echo ""
-					echo -e "\033[1;31mPort ไม่ถูกต้อง!"
+					echo -e "\033[1;31mPorta invalida!"
 					sleep 2
 					clear
 					fun_conexao
 				}
 				verif_ptrs $porta
-				echo -e "\033[1;32mเปลี่ยน PORT SSL TUNNEL!"
+				echo -e "\033[1;32mALTERANDO PORTA SSL TUNNEL!"
 				var2=$(grep 'accept' /etc/stunnel/stunnel.conf | awk '{print $NF}')
 				sed -i "s/\b$var2\b/$porta/g" /etc/stunnel/stunnel.conf >/dev/null 2>&1
 				echo ""
 				fun_bar 'sleep 2'
 				echo ""
-				echo -e "\033[1;32mRESTART SSL TUNNEL!\n"
+				echo -e "\033[1;32mREINICIANDO SSL TUNNEL!\n"
 				fun_bar 'service stunnel4 restart' '/etc/init.d/stunnel4 restart'
 				echo ""
-				netstat -nltp | grep 'stunnel4' >/dev/null && echo -e "\033[1;32mเปลี่ยนPORT สำเร็จ!" || echo -e "\033[1;31mERRO INESPERADO!"
+				netstat -nltp | grep 'stunnel4' >/dev/null && echo -e "\033[1;32mPORTA ALTERADA COM SUCESSO !" || echo -e "\033[1;31mERRO INESPERADO!"
 				sleep 3.5s
 				clear
 				fun_conexao
 			}
 			[[ "$resposta" = '2' ]] && {
-				echo -e "\033[1;32mลบ SSL TUNNEL !\033[0m"
+				echo -e "\033[1;32mREMOVENDO O  SSL TUNNEL !\033[0m"
 				del_ssl() {
 					service stunnel4 stop
 					apt-get remove stunnel4 -y
@@ -715,88 +715,68 @@ refresh_pattern .               0       20%     4320
 					apt-get purge stunnel4 -y
 					rm -rf /etc/stunnel/stunnel.conf
 					rm -rf /etc/default/stunnel4
-					rm -rf /etc/stunnel/cert.cert
-					rm -rf /etc/stunnel/key.key
+					rm -rf /etc/stunnel/stunnel.pem
 				}
 				echo ""
 				fun_bar 'del_ssl'
 				echo ""
-				echo -e "\033[1;32mลบSSL TUNNEL สำเร็จ!\033[0m"
+				echo -e "\033[1;32mSSL TUNNEL REMOVIDO COM SUCESSO!\033[0m"
+				sleep 3
+				fun_conexao
+			} || {
+				echo -e "\033[1;31mRetornando...\033[0m"
 				sleep 3
 				fun_conexao
 			}
 		else
 			clear
-			echo -e "\E[44;1;37m              INSTALL SSL TUNNEL               \E[0m"
+			echo -e "\E[44;1;37m           INSTALADOR SSL TUNNEL             \E[0m"
+			echo -e "\n\033[1;33mVC ESTA PRESTES A INSTALAR O SSL TUNNEL !\033[0m"
 			echo ""
-			echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mINSTALL SSL TUNNEL 033[0m"
-			echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mINSTALL SSL TUNNEL WEBSOCKET\033[0m"
-			echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mย้อนกลับ\033[0m"
-			echo ""
-			echo -ne "\033[1;32mSELLECT OPTION \033[1;33m?\033[1;37m "
+			echo -ne "\033[1;32mDESEJA CONTINUAR \033[1;31m? \033[1;33m[s/n]:\033[1;37m "
 			read resposta
-			echo ""
-			if [[ "$resposta" = '1' ]]; then
-				portssl='22'
-			elif [[ "$resposta" = '2' ]]; then
-				portssl='80'
-			elif [[ "$resposta" = '0' ]]; then
-				echo -e "\033[1;31mย้อนกลับ...\033[0m"
-				sleep 3
-				fun_conexao
-			else
+			[[ "$resposta" = 's' ]] && {
+				echo -e "\n\033[1;33mDEFINA UMA PORTA PARA O SSL TUNNEL !\033[0m"
 				echo ""
-				echo -e "\033[1;31mกรุณาเลือกให้ถูกต้อง !\033[0m"
-				sleep 1
-				inst_ssl
-			fi
-			clear
-			echo -e "\E[44;1;37m           INSTALL SSL TUNNEL             \E[0m"
-			echo -e "\n\033[1;33mVC คุณกำลังจะติดตั้ง SSL TUNNEL !\033[0m"
-			echo ""
-			echo -ne "\033[1;32mยืนยั้นการติดตั้ง \033[1;31m? \033[1;33m[y/n]:\033[1;37m "
-			read resposta
-			[[ "$resposta" = 'y' ]] && {
-				echo -e "\n\033[1;33mกำหนดพอร์ตสำหรับ SSL TUNNEL !\033[0m"
-				echo ""
-				read -p "$(echo -e "\033[1;32mพิมพ์ PORTที่ต้องใช้? \033[1;37m")" -e -i 443 porta
+				read -p "$(echo -e "\033[1;32mQUAL PORTA DESEJA UTILIZAR? \033[1;37m")" -e -i 443 porta
 				[[ -z "$porta" ]] && {
 					echo ""
-					echo -e "\033[1;31mPort ไม่ถูกต้อง!"
+					echo -e "\033[1;31mPorta invalida!"
 					sleep 3
 					clear
 					fun_conexao
 				}
 				verif_ptrs $porta
-				echo -e "\n\033[1;32mกำลังติดตั้ง SSL TUNNEL !\033[1;33m"
+				echo -e "\n\033[1;32mINSTALANDO O SSL TUNNEL !\033[1;33m"
 				echo ""
 				fun_bar 'apt-get update -y' 'apt-get install stunnel4 -y'
-				echo -e "\n\033[1;32mจัดการ SSL TUNNEL !\033[0m"
+				echo -e "\n\033[1;32mCONFIGURANDO O SSL TUNNEL !\033[0m"
 				echo ""
 				ssl_conf() {
-					echo -e "cert = /etc/stunnel/stunnel.pem\nclient = no\nsocket = a:SO_REUSEADDR=1\nsocket = l:TCP_NODELAY=1\nsocket = r:TCP_NODELAY=1\n\n[stunnel]\nconnect = 127.0.0.1:${portssl}\naccept = ${porta}" >/etc/stunnel/stunnel.conf
+					echo -e "cert = /etc/stunnel/stunnel.pem\nclient = no\nsocket = a:SO_REUSEADDR=1\nsocket = l:TCP_NODELAY=1\nsocket = r:TCP_NODELAY=1\n\n[stunnel]\nconnect = 0.0.0.0:22\naccept = ${porta}\nsslVersion = all" >/etc/stunnel/stunnel.conf
 				}
 				fun_bar 'ssl_conf'
-				echo -e "\n\033[1;32mการสร้างใบรับรอง !\033[0m"
+				echo -e "\n\033[1;32mCRIANDO CERTIFICADO !\033[0m"
 				echo ""
 				ssl_certif() {
-					crt='EC'
-					openssl genrsa -out key.pem 2048 >/dev/null 2>&1
-					(
-						echo $crt
-						echo $crt
-						echo $crt
-						echo $crt
-						echo $crt
-						echo $crt
-						echo $crt
-					) | openssl req -new -x509 -key key.pem -out cert.pem -days 1050 >/dev/null 2>&1
-					cat cert.pem key.pem >>/etc/stunnel/stunnel.pem
-					rm key.pem cert.pem >/dev/null 2>&1
+					#crt='EC'
+					#openssl genrsa -out key.pem 2048 >/dev/null 2>&1
+					#(
+					#echo $crt
+					#echo $crt
+					#echo $crt
+					#echo $crt
+					#echo $crt
+					#echo $crt
+					#echo $crt
+					#) | openssl req -new -x509 -key key.pem -out cert.pem -days 1050 >/dev/null 2>&1
+					#cat cert.pem key.pem >>/etc/stunnel/stunnel.pem
+					#rm key.pem cert.pem >/dev/null 2>&1
 					sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
+					cd /etc/stunnel && wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/SSHPLUS-MANAGER-FREE/master/Install/stunnel.pem && cd $HOME
 				}
 				fun_bar 'ssl_certif'
-				echo -e "\n\033[1;32mเริ่มต้นSSL TUNNEL !\033[0m"
+				echo -e "\n\033[1;32mINICIANDO O SSL TUNNEL !\033[0m"
 				echo ""
 				fun_finssl() {
 					service stunnel4 restart
@@ -804,36 +784,19 @@ refresh_pattern .               0       20%     4320
 					/etc/init.d/stunnel4 restart
 				}
 				fun_bar 'fun_finssl' 'service stunnel4 restart'
-				echo -e "\n\033[1;32mติดตั้งSSL TUNNEL สำเร็จ!\033[1;31m PORTA: \033[1;33m$porta\033[0m"
-				sleep 1
+				echo -e "\n\033[1;32mSSL TUNNEL INSTALADO COM SUCESSO !\033[1;31m PORTA: \033[1;33m$porta\033[0m"
+				sleep 3
 				clear
-				echo -e "Corrigindo SSL CLARO"
-				cd /etc/stunnel/
-				rm -rf stunnel.conf
-				rm -rf stunnel.pem
-				wget https://kguza.net/sshplus-vip/Install/cert
-				wget https://kguza.net/sshplus-vip/Install/key
-				wget https://kguza.net/sshplus-vip/Install/stunnel
-				mv cert cert.pem
-				mv key key.pem
-				mv stunnel stunnel.conf
-				chmod 777 cert.pem
-				chmod 777 key.pem
-				chmod 777 stunnel.conf
-				service stunnel4 restart
-				cd $HOME
-				clear
-				echo -e "Corrigido"
-				sleep 2
 				fun_conexao
 			} || {
-				echo -e "\n\033[1;31mย้อนกลับ...\033[0m"
+				echo -e "\n\033[1;31mRetornando...\033[0m"
 				sleep 2
 				clear
 				fun_conexao
 			}
 		fi
 	}
+	
 
 	fun_openvpn() {
 		if readlink /proc/$$/exe | grep -qs "dash"; then
