Update conexao

diff --git a/MODULOS/conexao b/MODULOS/conexao
--- a/MODULOS/conexao
+++ b/MODULOS/conexao
@@ -129,28 +129,52 @@ if [[ -z "$portass" ]]; then
 	sleep 3
 	fun_conexao
 fi
+
+
+
 for porta in $(echo -e $portass); do
-	verif_ptrs $porta
-done
-echo -e "\n\033[1;32mติดตั้ง SQUID PROXY\033[0m"
-fun_bar 'apt update -y' 'apt-get -y install squid'
-sleep 1
-if [[ -d "/etc/squid/" ]]; then
-var_sqd="/etc/squid/squid.conf"
-var_pay="/etc/squid/payload.txt"
-elif [[ -d "/etc/squid3/" ]]; then
-var_sqd="/etc/squid3/squid.conf"
-var_pay="/etc/squid3/payload.txt"
-fi
-echo ".claro.com.br/
-.claro.com.sv/
-.facebook.net/
-.netclaro.com.br/
-.speedtest.net/
-.tim.com.br/
-.vivo.com.br/
-.oi.com.br/" > $var_pay
-echo "acl localhost src 127.0.0.1/32 ::1
+				verif_ptrs $porta
+			done
+			[[ $(grep -wc '14' /etc/issue.net) != '0' ]] || [[ $(grep -wc '8' /etc/issue.net) != '0' ]] && {
+				echo -e "\n\033[1;32mINSTALANDO SQUID PROXY\033[0m\n"
+				fun_bar 'apt update -y' "apt install squid -yy"
+			} || {
+				echo -e "\n\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mSQUID VERSAO 3.3.X\n\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mSQUID VERSAO 3.5.X\033[0m\n"
+				read -p "$(echo -e "\033[1;32mINFORME UMA OPÇÃO \033[1;37m: ")" -e -i 1 opc
+				[[ -z "$opc" ]] && {
+					echo -e "\n\033[1;31mOpcao invalida!"
+					sleep 2
+					fun_conexao
+				}
+				[[ "$opc" != '1' ]] && {
+					[[ "$opc" != '2' ]] && {
+						echo -e "\n\033[1;31mOpcao invalida !"
+						sleep 2
+						fun_conexao
+					}
+				}
+				echo -e "\n\033[1;32mINSTALANDO SQUID PROXY\033[0m\n"
+				fun_bar 'apt update -y' "instsqd $opc"
+			}
+			if [[ -d "/etc/squid/" ]]; then
+				var_sqd="/etc/squid/squid.conf"
+				var_pay="/etc/squid/payload.txt"
+			elif [[ -d "/etc/squid3/" ]]; then
+				var_sqd="/etc/squid3/squid.conf"
+				var_pay="/etc/squid3/payload.txt"
+			else
+				echo -e "\n\033[1;33m[\033[1;31mERRO\033[1;33m]\033[1;37m: \033[1;33mO SQUID PROXY CORROMPEU\033[0m"
+				sleep 2
+				fun_conexao
+			fi
+cat <<-EOF >$var_pay
+				.whatsapp.net/
+				.facebook.net/
+				.twitter.com/
+				.speedtest.net/
+			EOF
+			cat <<-EOF >$var_sqd
+acl localhost src 127.0.0.1/32 ::1
 acl to_localhost dst 127.0.0.0/8 0.0.0.0/32 ::1
 acl localnet src 10.0.0.0/8
 acl localnet src 172.16.0.0/12
@@ -171,6 +195,7 @@ acl Safe_ports port 777
 acl CONNECT method CONNECT
 acl SSH dst $ipdovps-$ipdovps/255.255.255.255
 http_access allow SSH
+http_access allow payload
 http_access allow localnet
 http_access allow localhost
 http_access allow url1
@@ -179,37 +204,144 @@ refresh_pattern ^ftp:           1440    20%     10080
 refresh_pattern ^gopher:        1440    0%      1440
 refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
 refresh_pattern .               0       20%     4320
- 
-#Portas" > $var_sqd
+     #Portas
+EOF
 for Pts in $(echo -e $portass); do
-echo -e "http_port $Pts" >> $var_sqd
-[[ -f "/usr/sbin/ufw" ]] && ufw allow $Pts/tcp
-done
-echo -e "
-#Nome squid
-visible_hostname LiLGunX 
-via off
-forwarded_for off
-pipeline_prefetch off" >> $var_sqd
-sqd_conf () {
-if [[ -d "/etc/squid/" ]]; then
-squid -k reconfigure
-service ssh restart
-service squid restart
-elif [[ -d "/etc/squid3/" ]]; then
-squid3 -k reconfigure
-service ssh restart
-service squid3 restart
-fi
-}
-echo -e "\n\033[1;32mตั้งค่า SQUID PROXY\033[0m"
-echo ""
-fun_bar 'sqd_conf'
-echo -e "\n\033[1;32mติดตั้ง SQUID PROXY เรียบร้อยแล้ว!\033[0m"
-sleep 3.5s
-fun_conexao
-fi
-}
+				echo -e "http_port $Pts" >>$var_sqd
+				[[ -f "/usr/sbin/ufw" ]] && ufw allow $Pts/tcp
+			done
+			cat <<-EOF >>$var_sqd
+				#Nome squid
+				visible_hostname LiLGunX
+				via off
+				forwarded_for off
+				pipeline_prefetch off
+			EOF
+			sqd_conf() {
+				[[ -d "/etc/squid/" ]] && {
+					service ssh restart
+					/etc/init.d/squid restart
+					service squid restart
+				}
+				[[ -d "/etc/squid3/" ]] && {
+					service ssh restart
+					/etc/init.d/squid3 restart
+					service squid3 restart
+				}
+			}
+			echo -e "\n\033[1;32mCONFIGURANDO SQUID PROXY\033[0m"
+			echo ""
+			fun_bar 'sqd_conf'
+			echo -e "\n\033[1;32mSQUID INSTALADO COM SUCESSO!\033[0m"
+			sleep 2.5s
+			fun_conexao
+		fi
+	}
+for porta in $(echo -e $portass); do
+				verif_ptrs $porta
+			done
+			[[ $(grep -wc '14' /etc/issue.net) != '0' ]] || [[ $(grep -wc '8' /etc/issue.net) != '0' ]] && {
+				echo -e "\n\033[1;32mINSTALANDO SQUID PROXY\033[0m\n"
+				fun_bar 'apt update -y' "apt install squid -yy"
+			} || {
+				echo -e "\n\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mSQUID VERSAO 3.3.X\n\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mSQUID VERSAO 3.5.X\033[0m\n"
+				read -p "$(echo -e "\033[1;32mINFORME UMA OPÇÃO \033[1;37m: ")" -e -i 1 opc
+				[[ -z "$opc" ]] && {
+					echo -e "\n\033[1;31mOpcao invalida!"
+					sleep 2
+					fun_conexao
+				}
+				[[ "$opc" != '1' ]] && {
+					[[ "$opc" != '2' ]] && {
+						echo -e "\n\033[1;31mOpcao invalida !"
+						sleep 2
+						fun_conexao
+					}
+				}
+				echo -e "\n\033[1;32mINSTALANDO SQUID PROXY\033[0m\n"
+				fun_bar 'apt update -y' "instsqd $opc"
+			}
+			if [[ -d "/etc/squid/" ]]; then
+				var_sqd="/etc/squid/squid.conf"
+				var_pay="/etc/squid/payload.txt"
+			elif [[ -d "/etc/squid3/" ]]; then
+				var_sqd="/etc/squid3/squid.conf"
+				var_pay="/etc/squid3/payload.txt"
+			else
+				echo -e "\n\033[1;33m[\033[1;31mERRO\033[1;33m]\033[1;37m: \033[1;33mO SQUID PROXY CORROMPEU\033[0m"
+				sleep 2
+				fun_conexao
+			fi
+cat <<-EOF >$var_pay
+				.whatsapp.net/
+				.facebook.net/
+				.twitter.com/
+				.speedtest.net/
+			EOF
+			cat <<-EOF >$var_sqd
+acl localhost src 127.0.0.1/32 ::1
+acl to_localhost dst 127.0.0.0/8 0.0.0.0/32 ::1
+acl localnet src 10.0.0.0/8
+acl localnet src 172.16.0.0/12
+acl localnet src 192.168.0.0/16
+acl url1 dstdomain -i 127.0.0.1
+acl payload url_regex -i "$var_pay"
+acl SSL_ports port 443
+acl Safe_ports port 80
+acl Safe_ports port 21
+acl Safe_ports port 443
+acl Safe_ports port 70
+acl Safe_ports port 210
+acl Safe_ports port 1025-65535
+acl Safe_ports port 280
+acl Safe_ports port 488
+acl Safe_ports port 591
+acl Safe_ports port 777
+acl CONNECT method CONNECT
+acl SSH dst $ipdovps-$ipdovps/255.255.255.255
+http_access allow SSH
+http_access allow payload
+http_access allow localnet
+http_access allow localhost
+http_access allow url1
+http_access deny all
+refresh_pattern ^ftp:           1440    20%     10080
+refresh_pattern ^gopher:        1440    0%      1440
+refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
+refresh_pattern .               0       20%     4320
+     #Portas
+EOF
+for Pts in $(echo -e $portass); do
+				echo -e "http_port $Pts" >>$var_sqd
+				[[ -f "/usr/sbin/ufw" ]] && ufw allow $Pts/tcp
+			done
+			cat <<-EOF >>$var_sqd
+				#Nome squid
+				visible_hostname LiLGunX
+				via off
+				forwarded_for off
+				pipeline_prefetch off
+			EOF
+			sqd_conf() {
+				[[ -d "/etc/squid/" ]] && {
+					service ssh restart
+					/etc/init.d/squid restart
+					service squid restart
+				}
+				[[ -d "/etc/squid3/" ]] && {
+					service ssh restart
+					/etc/init.d/squid3 restart
+					service squid3 restart
+				}
+			}
+			echo -e "\n\033[1;32mCONFIGURANDO SQUID PROXY\033[0m"
+			echo ""
+			fun_bar 'sqd_conf'
+			echo -e "\n\033[1;32mSQUID INSTALADO COM SUCESSO!\033[0m"
+			sleep 2.5s
+			fun_conexao
+		fi
+	}
 
 addpt_sqd () {
 	echo -e "\E[44;1;37m         เพิ่ม Port Proxy         \E[0m"
